# Generated by Django 5.2.2 on 2025-06-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(blank=True)),
                ("title", models.CharField()),
                ("location", models.CharField()),
                ("description", models.TextField()),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("salary", models.IntegerField(blank=True, null=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("alternance", "Alternance"),
                            ("cdd", "CDD"),
                            ("cdi", "CDI"),
                            ("freelance", "Freelance"),
                            ("interim", "Intérim"),
                        ]
                    ),
                ),
            ],
        ),
    ]
